project:
  type: website
  output-dir: docs

website:
  title: "LDC"
  navbar:
    logo: mylogo_website_simple.png
    right:
      - about.qmd
      - Research.qmd
      - Teaching.qmd
      - Publications.qmd
      - posts.qmd
      - Contact.qmd
  page-footer: 
    background: light
    left: Â© 2026 Ludovic De Cuypere
    right: This website is built with [RStudio](https://www.r-project.org/about.html){target=_blank} and [Quarto](https://quarto.org/){target=_blank}

format:
  html:
    theme: [lux, mystyle_main.scss]
    mainfont: EB+Garamond
    fontsize: 1.1em
    toc: true
