project:
  type: website
  output-dir: docs

website:
  title: "Ludovic De Cuypere"
  navbar:
    right:
      - about.qmd
      - Presentations.qmd
      - Teaching.qmd
      - Research.qmd
      - href: CV.pdf
        text: CV
  page-footer: 
    background: light
    left: Â© 2026 Ludovic De Cuypere
    right: This website is built with (https://www.r-project.org/about.html){target=_blank} and [Quarto](https://quarto.org/){target=_blank}

format:
  html:
    theme:
      light: lux
      dark: darkly
    css: styles.css
    toc: true



