project:
  type: website
  output-dir: docs

website:
  title: "Ludovic De Cuypere"
  description: "Personal website of Ludovic De Cuypere"
  navbar:
    right:
      - about.qmd
      - Research.qmd
      - Talks_and_Workshops.qmd
      - Teaching.qmd
      - posts.qmd
      - Contact.qmd
  page-footer: 
    background: light
    left: Â© 2026 Ludovic De Cuypere
    right: This website is built with [RStudio](https://www.r-project.org/about.html){target=_blank} and [Quarto](https://quarto.org/){target=_blank}

format:
  html:
    theme: [Journal, mystyle_main.scss]
    mainfont: EB+Garamond
    toc: true
    toc-depth: 2
    toc-title: "Contents"
    toc-font-size: 0.9rem

execute:
  freeze: auto